name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build steps here
      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

      # Add additional steps for build, test, deploy, etc.

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deploy to production
        # Add deployment steps here
        run: |
          echo "Deploying to production..."
